FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json* ./
COPY apps/backend/package.json ./apps/backend/

RUN npm install --workspace @aula-marcada/backend

COPY apps/backend ./apps/backend

WORKDIR /app/apps/backend

RUN npm run prisma:generate

EXPOSE 3333

CMD ["npm", "run", "dev"]
